### ISSUE TITLE
High Sierra MAC OS issue

### ISSUE THREAD

**Issue by 2ge** [ConsulTent/Bitcloud#2]
as discussed here:
https://github.com/LIMXTEC/Bitcloud/issues/15#issuecomment-461665735

screenshots on high sierra:

![image](https://user-images.githubusercontent.com/1067032/52461961-c9fd6000-2ba3-11e9-8800-d0bd56a69258.png)

![image](https://user-images.githubusercontent.com/1067032/52461954-bf42cb00-2ba3-11e9-9df6-dde94e8ffc3d.png)

**Comment by azilber** [comment]
I've updated the binary minimum release version.  Try re-downloading it again.  It should work now!

**Comment by 2ge** [comment]
yes, this is working also on high sierra, looking good!
